[build]
    functions = "/functions/"
    command = "npm run build"
[[redirects]]
    from = "/javascript-array-prototype-methods-from-explained/"
    to = "/blog/javascript-array-methods-from-explained/"
    status = 301
    force = false
    
[[redirects]]
    from = "/javascript-array-methods-from-explained/"
    to = "/blog/javascript-array-methods-from-explained/"
    status = 301
    force = false

[[redirects]]
    from = "/javascript-array-prototype-methods-isarray-explained/"
    to = "/blog/javascript-array-methods-isarray-explained/"
    status = 301
    force = false

[[redirects]]
    from = "/javascript-array-methods-isarray-explained/"
    to = "/blog/javascript-array-methods-isarray-explained/"
    status = 301
    force = false

[[redirects]]
    from = "/javascript-fundamentals-functions-overview/"
    to = "/blog/javascript-fundamentals-functions-overview/"
    status = 301
    force = false
    
[[redirects]]
    from = "/javascript-fundamentals-getters-setters/"
    to = "/blog/javascript-fundamentals-getters-setters/"
    status = 301
    force = false
    
[[redirects]]
    from = "/finding-updating-outdated-npm-packages/"
    to = "/blog/finding-updating-outdated-npm-packages/"
    status = 301
    force = false

[[redirects]]
    from = "/gatsby-blog-open-graph-image/"
    to = "/blog/gatsby-blog-open-graph-image/"
    status = 301
    force = false

[[redirects]]
    from = "/changing-vscode-menu-bar-colour/"
    to = "/blog/changing-vscode-menu-bar-colour/"
    status = 301
    force = false

[[redirects]]
    from = "/deleting-files-node-js-promises/"
    to = "/blog/deleting-files-node-js-promises/"
    status = 301
    force = false

[[redirects]]
    from = "/javascript-array-methods-of-explained/"
    to = "/blog/javascript-array-methods-of-explained/"
    status = 301
    force = false

[[redirects]]
    from = "/gatsby-mdx-blog-rss-feed/"
    to = "/blog/gatsby-mdx-blog-rss-feed/"
    status = 301
    force = false

[[redirects]]
    from = "/javascript-array-methods-prototype-concat-explained/"
    to = "/blog/javascript-array-methods-prototype-concat-explained/"
    status = 301
    force = false
    
[[redirects]]
    from = "/optimising-google-fonts-gatsby-increased-performance/"
    to = "/blog/optimising-google-fonts-gatsby-increased-performance/"
    status = 301
    force = false
    
[[redirects]]
    from = "/javascript-array-methods-prototype-copywithin-explained/"
    to = "/blog/javascript-array-methods-prototype-copywithin-explained/"
    status = 301
    force = false
    
[[redirects]]
    from = "/netlify-redirects-gatsby-website/"
    to = "/blog/netlify-redirects-gatsby-website/"
    status = 301
    force = false
    
[[redirects]]
    from = "/javascript-array-methods-prototype-entries-explained/"
    to = "/blog/javascript-array-methods-prototype-entries-explained/"
    status = 301
    force = false

[[redirects]]
    from = "/gatsby-develop-npm-run-develop/"
    to = "/blog/gatsby-develop-npm-run-develop/"
    status = 301
    force = false

[[redirects]]
    from = "/javascript-array-methods-prototype-every-explained/"
    to = "/blog/javascript-array-methods-prototype-every-explained/"
    status = 301
    force = false

[[redirects]]
    from = "/javascript-array-methods-prototype-fill-explained/"
    to = "/blog/javascript-array-methods-prototype-fill-explained/"
    status = 301
    force = false

[[redirects]]
    from = "/how-to-schedule-tweets-on-android-ios/"
    to = "/blog/how-to-schedule-tweets-on-android-ios/"
    force = false
    status = 301

[[redirects]]
    from = "/Javascript-Fundamentals-Getters-Setters/"
    to = "/blog/javascript-fundamentals-getters-setters/"
    force = false
    status = 301
    
[[redirects]]
    from = "/JavaScript-Fundamentals-Functions-Overview/"
    to = "/blog/javascript-fundamentals-functions-overview/"
    force = false
    status = 301

[[redirects]]
    from = "/reads"
    to = "/"
    force = false
    status = 410

[[redirects]]
    from = "/notes"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "/notes/javascript/prototypal-inheritance/"
    to = "/blog/prototypal-inheritance-overview"
    force = false
    status = 301

[[redirects]]
    from = "/notes/javascript/higher-order-functions/"
    to = "/blog/javascript-higher-order-functions-overview"
    force = false
    status = 301

[[redirects]]
    from = "/notes/javascript/first-class-functions/"
    to = "/blog/javascript-first-class-functions-overview"
    force = false
    status = 301

[[redirects]]
    from = "/notes/r/vectors-overview/"
    to = "/blog/r-vectors-overview"
    force = false
    status = 301

[[redirects]]
    from = "blog/javascript"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "blog/javascript/2"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "blog/gatsbyjs"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "blog/gatsbyjs/2"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "blog/other"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "blog/blogging"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "blog/nodejs"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "blog/web-development"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "notes/javascript"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "notes/r"
    to = "/blog"
    force = false
    status = 301

[[redirects]]
    from = "/portfolio"
    to = "/projects"
    force = false
    status = 301

[[redirects]]
    from = "/portfolio/gatsbyjs"
    to = "/projects"
    force = false
    status = 301

[[redirects]]
    from = "/portfolio/graphql"
    to = "/projects"
    force = false
    status = 301

[[redirects]]
    from = "/portfolio/nodejs"
    to = "/projects"
    force = false
    status = 301

[[redirects]]
    from = "/portfolio/next.js"
    to = "/projects"
    force = false
    status = 301

[[redirects]]
    from = "/threads/book-recommendations"
    to = "/threads"
    force = false
    status = 410

[[redirects]]
    from = "/threads/feedhive-impressions"
    to = "/threads"
    force = false
    status = 410

[[redirects]]
    from = "/threads/blog-posts-cross-posting"
    to = "/threads/post-cross-posting"
    force = false
    status = 301

[[redirects]]
    from = "/threads/javascript"
    to = "/threads"
    force = false
    status = 301

[[redirects]]
    from = "/threads/javascript/2"
    to = "/threads"
    force = false
    status = 301

[[redirects]]
    from = "/threads/gatsbyjs"
    to = "/threads"
    force = false
    status = 301

[[redirects]]
    from = "/threads/blogging"
    to = "/threads"
    force = false
    status = 301

[[redirects]]
    from = "/threads/other"
    to = "/threads"
    force = false
    status = 301

[[redirects]]
    from = "/threads/r"
    to = "/threads"
    force = false
    status = 301

[[redirects]]
    from = "/threads/graphql"
    to = "/threads"
    force = false
    status = 301

[[redirects]]
    from = "/threads/nodejs"
    to = "/threads"
    force = false
    status = 301