name: Build

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: npm install

      - name: install packages dependencies
        run: npm install
        working-directory: ./backend

      - name: Install CDK
        run: npm i -g aws-cdk

      - name: build frontend
        run: cdk synth
        working-directory: ./backend
