name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  tests_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install root dependencies
        run: npm install

      - name: install packages dependencies
        run: npm install
        working-directory: ./frontend

      - name: run tests
        run: npm run test:coverage
        working-directory: ./frontend

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install dependencies
        run: npm install

      - name: install packages dependencies
        run: npm install
        working-directory: ./backend

      - name: Install CDK
        run: npm i -g aws-cdk

      - name: build frontend
        run: cdk synth
        working-directory: ./backend

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install root dependencies
        run: npm ci

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint
        run: npm run lint
